// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/price/price.proto

package pricepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetQuoteRequest carries the symbol the caller wants a quote for.
type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_proto_price_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_price_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetQuoteResponse carries the current simulated price for a symbol.
type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_proto_price_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_price_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetQuoteResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetQuoteResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_proto_price_price_proto protoreflect.FileDescriptor

const file_proto_price_price_proto_rawDesc = "" +
	"\n" +
	"\x17proto/price/price.proto\x12\x05price\")\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"g\n" +
	"\x10GetQuoteResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix2K\n" +
	"\fPriceService\x12;\n" +
	"\bGetQuote\x12\x16.price.GetQuoteRequest\x1a\x17.price.GetQuoteResponseBPZNgithub.com/GabrielHKGodinho/investment-engine/internal/priceservice/pb;pricepbb\x06proto3"

var (
	file_proto_price_price_proto_rawDescOnce sync.Once
	file_proto_price_price_proto_rawDescData []byte
)

func file_proto_price_price_proto_rawDescGZIP() []byte {
	file_proto_price_price_proto_rawDescOnce.Do(func() {
		file_proto_price_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_price_price_proto_rawDesc), len(file_proto_price_price_proto_rawDesc)))
	})
	return file_proto_price_price_proto_rawDescData
}

var file_proto_price_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_price_price_proto_goTypes = []any{
	(*GetQuoteRequest)(nil),  // 0: price.GetQuoteRequest
	(*GetQuoteResponse)(nil), // 1: price.GetQuoteResponse
}
var file_proto_price_price_proto_depIdxs = []int32{
	0, // 0: price.PriceService.GetQuote:input_type -> price.GetQuoteRequest
	1, // 1: price.PriceService.GetQuote:output_type -> price.GetQuoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_price_price_proto_init() }
func file_proto_price_price_proto_init() {
	if File_proto_price_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_price_price_proto_rawDesc), len(file_proto_price_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_price_price_proto_goTypes,
		DependencyIndexes: file_proto_price_price_proto_depIdxs,
		MessageInfos:      file_proto_price_price_proto_msgTypes,
	}.Build()
	File_proto_price_price_proto = out.File
	file_proto_price_price_proto_goTypes = nil
	file_proto_price_price_proto_depIdxs = nil
}
